<?php
/**
 * @file
 * Code for the PCOM_Custom module.
 */

/*Updates Proximity Search to only include Miles and KM*/

function pcom_custom_form_views_exposed_form_alter(&$form, &$form_state, $form_id) {
  if (isset($form['field_geofield_distance_1'])) {
    // $existing =
    $form['field_geofield_distance_1']['#process'] = array(
      'geofield_proximity_element_process',
      'pcom_custom_proximity_element_process');
  }
}

function pcom_custom_proximity_element_process($element, &$form_state, $form) {
//dpm($form);
  $element['unit']['#options'] = array(
    GEOFIELD_MILES => t('Miles'),
    GEOFIELD_KILOMETERS => t('Kilometers'));
  return $element;
}

/* End of Proximity search fix */


/* This fixes the Featured Media taxonomy/images on basic pages */
function pcom_custom_form_alter(&$form, &$form_state, $form_id) {
	if($form['#form_id']=='page_node_form' && $form['type']['#value']=='page') {

		$Nasdfasdf=node_load($form['nid']['#value']);
		$Poop=$Nasdfasdf->field_featured['und'][0]['tid'];
		$form['field_featured']['und']['#default_value'][0]=$Poop;
		$vocabulary = taxonomy_vocabulary_machine_name_load('featured_media');
		$terms = entity_load('taxonomy_term', FALSE, array('vid' => $vocabulary->vid));
		$termdeets=array();

	foreach($terms as $termid => $termname) {
		$termdeets[$termid]=$termname->name;
	}
	$form['field_featured']['und']['#options']=$termdeets;
}
}

/* For events we want to append the date to the end of the title (and remove 'Clone of' if applicable) upon node submit */

function pcom_custom_node_submit($node) {
	if ($node->type == 'event') {
		if (strpos($node->title, 'Clone of') !== FALSE) {
			$title1 = str_replace('Clone of ', '', $node->title);
		}
		else {
			$title1 = $node->title;
		}
			
		$title = $title1.' '.format_date(strtotime($node->field_date['und'][0]['value']), 'custom', 'F d, Y');
 		$node->title = $title; 
  }
}

/* Insert metatag for event views. */

function pcom_custom_views_pre_view(&$view, &$display_id, &$args) {
	//dpm($view);
	if($view->name == 'articles' && $view->current_display == 'blog') {
		//dpm($view);
		$metainsert = "Here is a list of Pacific College blog posts from ".$view->args[2]." ".$view->args[1]."-".$view->args[0]." Click here to see what was published during this time.";
		$element = array(
		'#type' => 'html_tag',
		'#tag' => 'meta', // The #tag is the html tag - 
		'#attributes' => array( // Set up an array of attributes inside the tag
			'name' => 'description', 
			'content' => $metainsert
  )
);
drupal_add_html_head($element, 'metainstert');
		
	}

}
